config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  resources :pokemons do
  	member do
  		get 'add_pokemon'
  	end
  end
  resources :users do
  	resources :caughts do
  		member do
  			get 'lvl_up'
  		end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= pokemons_path %>">Pokemons</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><a href="<%=user_caughts_path(current_user)%>">Mis Pokemones</a></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="javascript:void(0)">Datos Personales</a></li>
            <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Salir</a></li>
          </ul>
          <% else %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Ingresa<span class="caret"></span>
          </a>
            <ul class="dropdown-menu">
            <li><a href="<%= new_user_registration_path %>">Registro</a></li>
            <li><a href="<%= new_user_session_path %>">Entrar</a></li>
          </ul>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>