config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  resources :pokemons do
  	member do
  		get 'add_pokemon'
  	end
  end
  resources :users do
  	resources :caughts do
  		member do
  			get 'lvl_up'
  		end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
end

app/models/caught.rb
class Caught < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user
end

app/controllers/caughts_controller.rb
class CaughtsController < ApplicationController
  before_action :set_caught, only: [:show, :edit, :update, :destroy, :lvl_up]

  # GET /caughts
  # GET /caughts.json
  def index
    @caughts = current_user.caughts
  end

  # GET /caughts/1
  # GET /caughts/1.json
  def show
  end

  # GET /caughts/new
  def new
    @caught = Caught.new
  end

  # GET /caughts/1/edit
  def edit
  end

  # POST /caughts
  # POST /caughts.json
  def create
    @caught = Caught.new(caught_params)

    respond_to do |format|
      if @caught.save
        format.html { redirect_to @caught, notice: 'Caught was successfully created.' }
        format.json { render :show, status: :created, location: @caught }
      else
        format.html { render :new }
        format.json { render json: @caught.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caughts/1
  # PATCH/PUT /caughts/1.json
  def update
    respond_to do |format|
      if @caught.update(caught_params)
        format.html { redirect_to user_caughts_path(params[:user_id]), notice: 'Caught was successfully updated.' }
        format.json { render :show, status: :ok, location: @caught }
      else
        format.html { render :edit }
        format.json { render json: @caught.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caughts/1
  # DELETE /caughts/1.json
  def destroy
    @caught.destroy
    respond_to do |format|
      format.html { redirect_to user_caughts_path(params[:user_id]), notice: 'Caught was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def lvl_up
    @caught.level+=1
    @caught.save
    redirect_to user_caughts_path(params[:user_id]), notice: 'Level was successfully updated.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caught
      @caught = Caught.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caught_params
      params.require(:caught).permit(:level, :pokemon_id)
    end
end

app/helpers/caughts_helper.rb
module CaughtsHelper
end

app/views/caughts/_form.html.erb
<%= form_for [current_user,caught] do |f| %>
  <% if caught.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caught.errors.count, "error") %> prohibited this caught from being saved:</h2>

      <ul>
      <% caught.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caughts/edit.html.erb
<h1>Editing Caught</h1>

<%= render 'form', caught: @caught %>

<%= link_to 'Show', user_caught_path(params[:user_id], @caught.id) %> 
<%= link_to 'Back', user_caughts_path(params[:user_id]) %>

app/views/caughts/index.html.erb
<h1><%= current_user.name %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Pokemon</th>
      <th>Current Level</th>
      <th>Level Up</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @caughts.each do |caught| %>
      <tr>
        <td><%= Pokemon.find(caught.pokemon_id).name%></td>
        <td><%= caught.level %></td>
        <td><%= link_to 'Level Up', lvl_up_user_caught_path(params[:user_id], caught) %>
        <td><%= link_to 'Show', user_caught_path(params[:user_id], caught.id) %></td>
        <td><%= link_to 'Edit', edit_user_caught_path(params[:user_id], caught) %></td>
        <td><%= link_to 'Destroy', user_caught_path(params[:user_id], caught), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', pokemons_path %>

app/views/caughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pokemon:</strong>
  <%= Pokemon.find(@caught.pokemon_id).name %>
</p>
<p>
  <strong>Level:</strong>
  <%= @caught.level %>
</p>

<%= link_to 'Edit', edit_user_caught_path(params[:user_id], @caught) %> |
<%= link_to 'Back', user_caughts_path(params[:user_id])%>